name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'

env:
  CC: gcc

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: |
          make fmt
      - name: test
        run: |
          make test
